on:
  push:
    branches:
      - master
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: calcit-lang/setup-calcit@6a2e53ae41e4f0d5856a424b9ed4470d90ea6876

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release

      - run: cargo clippy -- -D warnings

      - run: cargo test

      - run: rm -rfv dylibs/* && mkdir -p dylibs/ && ls target/release/ && cp -v target/release/*.* dylibs/

      - run: calcit calcit.cirru --check-only
      - run: calcit calcit.cirru --warn-dyn-method --check-only
      - run: calcit calcit.cirru analyze check-types --summary-only --format json
      - run: calcit calcit.cirru analyze weak-types --intent unresolved --summary-only --format json
      - run: calcit calcit.cirru analyze deprecated --summary-only --format json
